# Generated by Django 4.0.2 on 2022-06-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followerscount',
        ),
    ]
