# Generated by Django 4.0.2 on 2022-06-02 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followerscount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.followerscount'),
        ),
    ]
