# Generated by Django 4.0.2 on 2022-06-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_followerscount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='followerscount',
            new_name='fc',
        ),
    ]
