# Generated by Django 4.0.2 on 2022-06-02 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_followerscount_profile_fc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fc',
        ),
    ]
