# Generated by Django 4.0.2 on 2022-05-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_post_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
