# Generated by Django 4.0.2 on 2022-05-16 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_patricipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='patricipants',
            new_name='participants',
        ),
    ]
